global:
  scrape_interval: 10s  # 每10秒抓取一次

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'alarm'
    static_configs:
      - targets: ['host.docker.internal:6060'] 
