global:
  scrape_interval: 10s  # 每10秒抓取一次

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'task_backend'
    static_configs:
      - targets: ['host.docker.internal:9091']  # 指定宿主机的应用地址
  - job_name: 'task_mq'
    static_configs:
      - targets: ['host.docker.internal:9092']  # 指定宿主机的应用地址
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['host.docker.internal:9104']  # Redis Exporter 的监控目标
